apiVersion: connectivity.iotoperations.azure.com/v1
kind: DataflowEndpoint
metadata:
  name: mq-source
  namespace: default
spec:
  endpointType: mqtt
  mqttSettings:
    host: "aio-broker:8883"
    tls:
      mode: Enabled
      trustedCaCertificateConfigMapRef: aio-broker-ca
    maxInflightMessages: 10000
    authentication:
      method: ServiceAccountToken
      serviceAccountTokenSettings:
        audience: aio-mq-internal
---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: DataflowEndpoint
metadata:
  name: kafka-target
  namespace: default
spec:
  endpointType: kafka
  kafkaSettings:
    copyMqttProperties: Enabled
    cloudEventAttributes: CreateOrRemap
    host: $EVENTHUB_KAFKA_DOMAIN
    tls:
      mode: Enabled
    authentication:
      method: Sasl
      saslSettings:
        saslType: plain
        secretRef: "eh-secret"
---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: mq-to-kafka
  namespace: default
spec:
  profileRef: mq-eh-perf-flow
  operations:
    - operationType: source
      sourceSettings:
        endpointRef: mq-source
        dataSources:
        - source/#
    - operationType: destination
      destinationSettings:
        endpointRef: kafka-target
        dataDestination: $EVENTHUB_NAME
---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: DataflowProfile
metadata:
  name: mq-eh-perf-flow
  namespace: default
spec:
  instanceCount: 1
  diagnostics:
    logs:
      level: "trace"