apiVersion: connectivity.iotoperations.azure.com/v1
kind: DataflowEndpoint
metadata:
  name: mq-source
  namespace: default
spec:
  endpointType: mqtt
  mqttSettings:
    host: "aio-broker:8883"
    tls:
      mode: Enabled
      trustedCaCertificateConfigMapRef: aio-broker-ca
    maxInflightMessages: 10000
    authentication:
      method: ServiceAccountToken
      serviceAccountTokenSettings:
        audience: aio-mq-internal
---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: DataflowEndpoint
metadata:
  name: kafka-target
  namespace: default
spec:
  endpointType: kafka
  kafkaSettings:
    copyMqttProperties: Enabled
    cloudEventAttributes: CreateOrRemap
    host: "jkarangula2.servicebus.windows.net:9093"
    batching:
      mode: enabled
      latencyMs:  50
      maxMessages: 100000
    tls:
      mode: Enabled
    authentication:
      method: Sasl
      saslSettings:
        saslType: plain
        secretRef: "eh-secret"
---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: mq-to-kafka
  namespace: default
spec:
  profileRef: mq-eh-perf-flow
  operations:
    - operationType: source
      sourceSettings:
        endpointRef: mq-source
        dataSources:
        - source/#
    - operationType: destination
      destinationSettings:
        endpointRef: kafka-target
        dataDestination: test
---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: DataflowProfile
metadata:
  name: mq-eh-perf-flow
  namespace: default
spec:
  instanceCount: 15
  diagnostics:
    logs:
      level: "info"