apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: Broker
metadata:
  name: broker
  namespace: default
spec:
  advanced:
    encryptInternalTraffic: Disabled
  memoryProfile: "High"
  diskBackedMessageBuffer:
    maxSize: '25G'
    persistentVolumeClaimSpec:
      ## Default storage class `rancher.io/local-path` on k3d
      ## storageClassName: 'foo'
      accessModes:
      - 'ReadWriteOnce'
  cardinality:
    frontend:
      replicas: 1
      workers: 1
    backendChain:
      redundancyFactor: 1
      partitions: 1
      workers: 1
  diagnostics:
    logs:
      level: debug
    metrics:
      prometheusPort: 9600
    selfCheck:
      mode: Disabled
    traces:
      mode: Disabled
      selfTracing:
        mode: Enabled
        intervalSeconds: 60
  generateResourceLimits:
    cpu: Disabled
---
apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: "aio-broker"
  namespace: default
spec:
  brokerRef: broker
  serviceType: loadBalancer
  ports:
    - port: 1883
      protocol: mqtt
    - port: 8883
      protocol: mqtt
      tls:
        mode: Automatic
        certManagerCertificateSpec:
          issuerRef:
            name: aio-ca-issuer
            kind: Issuer
